
version: '3.7'

services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb_inc
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - docker-newtwork

  wordpress:
    build: ./requirements/wordpress
    image: wordpress_inc
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp-data:/var/www/wordpress/
    env_file:
      - .env
    networks:
      - docker-newtwork

  nginx:
    build: ./requirements/nginx
    image: nginx_inc
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/wordpress/
    networks:
      - docker-newtwork
    ports:
      - "443:443"
      - "80:80"
          
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer_inc
    container_name: adminer
    depends_on:
      - mariadb
    restart: always
    ports:
      - "8080:8080"
    networks:
     - docker-newtwork

  redis:
    build: ./requirements/bonus/redis
    image: redis_inc
    container_name: redis
    restart: always
    networks:
      - docker-newtwork

  # ftp:
  #   build: ./requirements/bonus/ftp
  #   image: ftp_inc
  #   container_name: vsftpd
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "21:21"
  #   volumes:
  #     - wp-data:/var/www/
  #   networks:
  #    - docker-newtwork
  #   restart: always
        
networks:

  docker-newtwork:
    driver: bridge

volumes:

  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wp
      
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/db