
version: '3.7'

services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb_inc
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - docker-newtwork

  wordpress:
    build: ./requirements/wordpress
    image: wordpress_inc
    container_name: wordpress
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - wp-data:/var/www/wordpress/
    env_file:
      - .env
    networks:
      - docker-newtwork

  nginx:
    build: ./requirements/nginx
    image: nginx_inc
    container_name: nginx
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/wordpress/
    networks:
      - docker-newtwork
    ports:
      - "443:443"
      - "80:80"
          
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer_inc
    container_name: adminer
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
     - docker-newtwork

  redis:
    build: ./requirements/bonus/redis
    image: redis_inc
    container_name: redis
    restart: unless-stopped
    networks:
      - docker-newtwork

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp_inc
    container_name: vsftpd
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "21:21"
      - "10100-10110:10100-10110"
    volumes:
      - wp-data:/var/www/wordpress
    networks:
     - docker-newtwork
    restart: unless-stopped

  # website:

  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor_inc
    container_name: cadvisor
    depends_on:
      - nginx
      - mariadb
      - wordpress
      - adminer
      - ftp
    ports:
      - "8090:8090"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - docker-network
    restart: unless-stopped

networks:

  docker-newtwork:
    driver: bridge

volumes:

  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wp
      
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/db