
version: '3.7'

services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb_inc
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - docker-newtwork

  wordpress:
    build: ./requirements/wordpress
    image: wordpress_inc
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp-data:/var/www/wordpress/
    env_file:
      - .env
    networks:
      - docker-newtwork

  nginx:
    build: ./requirements/nginx
    image: nginx_inc
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wp-data:/var/www/wordpress/
    networks:
      - docker-newtwork
    ports:
      - "443:443"
      - "80:80"
          
networks:

  docker-newtwork:
    driver: bridge

volumes:

  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/wp
      
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/db